name: Saucedemo Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Selenium Tests with Allure
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager allure-pytest

      # Step 4: Install Chrome dependencies for CI
      - name: Install Chrome and required libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip libnss3 libxss1 libappindicator3-1 fonts-liberation

          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      # Step 5: Install Allure Commandline
      - name: Install Allure Commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          tar -zxvf allure-2.29.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
          allure --version

      # Step 6: Run tests and collect Allure results
      - name: Run PyTest tests
        run: |
          mkdir -p reports/allure-results
          pytest --alluredir=reports/allure-results --disable-warnings -v

      # Step 7: Debug Allure results
      - name: List Allure Results
        run: |
          echo "Contents of Allure results:"
          ls -lR reports/allure-results

      # Step 8: Generate Allure Report
      - name: Generate Allure Report
        run: |
          mkdir -p reports/allure-report
          if [ "$(ls -A reports/allure-results)" ]; then
            allure generate reports/allure-results -o reports/allure-report --clean
            echo "✅ Allure report generated successfully at reports/allure-report"
          else
            echo "⚠️ No Allure results found!"
          fi

      # Step 9: Upload Allure Report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
