name: Saucedemo Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Selenium Tests with Allure
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager allure-pytest

      # Step 4: Install Chrome (for Selenium)
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      # Step 5: Run tests (headless mode)
      - name: Run PyTest tests
        run: |
          pytest --alluredir=reports/allure-results --disable-warnings -v

      # Step 6: Generate Allure Report
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: reports/allure-results
          allure_report: reports/allure-report
          allure_history: allure-history

      # Step 7: Upload Allure results as artifacts (for viewing/download)
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
