name: Saucedemo Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Selenium Tests with Allure
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests and collect allure results
      - name: Run PyTest tests
        run: |
          pytest --alluredir=reports/allure-results

      # Step 5: Generate Allure Report
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: reports/allure-results
          allure_report: reports/allure-report
          allure_history: allure-history

      # Step 6: Upload Allure results as artifacts (for viewing/download)
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-report

